<?php

namespace AppBundle\Repository;

/**
 * Event_target_dayRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Event_target_dayRepository extends \Doctrine\ORM\EntityRepository
{
}
