<?php

namespace AppBundle\Repository;

use Doctrine\Common\Collections\ArrayCollection;

/**
 * EventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventRepository extends \Doctrine\ORM\EntityRepository
{
    
    public function findByEventList()
    {
        $query = $this->createQueryBuilder('e')
                ->select('e.eventTitle, e.createAt, r.eventId')
                ->addSelect('(count(r.id)) AS answer')
                ->leftJoin('AppBundle:Rel_event_answer','r','WITH','e.id = r.eventId')
                ->groupBy('e.id')
                ->getQuery();
        
        return new ArrayCollection($query->getResult());
    }
    
}
