<?php

namespace AppBundle\Repository;

/**
 * Event_required_memberRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Event_required_memberRepository extends \Doctrine\ORM\EntityRepository
{
}
