<?php

namespace AppBundle\Repository;

/**
 * Rel_event_answerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Rel_event_answerRepository extends \Doctrine\ORM\EntityRepository
{
}
